<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Golang异常捕捉方法recover和panic | TJ&#39;s Blog</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    <header>

  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <nav>
    <ul>
      
      
      
      
      <li class="pull-left ">
        <a href="/">~/home</a>
      </li>
      
      
      <li class="pull-left ">
        <a href="/categories/">~/categories</a>
      </li>
      
      
      <li class="pull-left ">
        <a href="/tags/">~/tags</a>
      </li>
      

      
      
      <li class="pull-right">
        <a href="/index.xml">~/subscribe</a>
      </li>
      

    </ul>
  </nav>
</header>

  </head>

  <body>
    <br/>

<div class="article-meta">
<h1><span class="title">Golang异常捕捉方法recover和panic</span></h1>

<h2 class="date">2017/07/19</h2>
<p class="terms">
  
  
  Categories: <a href="/categories/dev">Dev</a> 
  
  
  
  Tags: <a href="/tags/golang">Golang</a> 
  
  
</p>
</div>



<main>


<p>go使用recover和panic作为异常捕获机制。</p>

<ul>
<li>panic可以是用户主动调用抛出异常，也可以是一般程序执行中发生的异常，如内存访问错误等。</li>
<li>recover用于捕获panic抛出的异常，特别的是recover只能放在defer的关键字声明的函数体中使用。类似于C++中的try-catch，panic抛出的异常可以被同一层的recover或者上一层的recover捕获，具体依赖于recover所在的位置。</li>
</ul>

<h3 id="recover和panic的定义">recover和panic的定义</h3>

<hr />

<pre><code class="language-go">//一般输出error类型
func recover() interface{}

//interface接受任何类型的输入
func panic(v ...interface{})
</code></pre>

<h3 id="测试代码">测试代码</h3>

<hr />

<pre><code class="language-go">func main() {
    defer func() {
        //catch exception
        if err := recover(); err != nil {
            fmt.Println(err)
        }
        //defer stack
        fmt.Println(&quot;first defer&quot;)
    }()

    defer func() {
        //defer stack
        fmt.Println(&quot;second defer&quot;)
    }()
    f()
}

func f() {
    a := []string{&quot;a&quot;, &quot;b&quot;}
    //throw exception
    defer func() {
        if err := recover(); err != nil {
            fmt.Println(&quot;f err = &quot;, err)
        }
    }()

    fmt.Println(a[3])
    //never reach
    fmt.Println(&quot;f end&quot;)
}
</code></pre>

</main>

    <footer>
      
<script async src="//yihui.name/js/center-img.js"></script>

      
      <hr/>
      Open-Source | <a href="https://github.com/kristd">Github</a>
      
    </footer>
  </body>
</html>

